[package]
name = "doge-wallet"
version = "0.1.0"
edition = "2018"
authors = ["Tobin Harding <me@tobin.cc>"]
license = "MIT"
homepage = "https://github.com/tcharding/doge-wallet-rs/"
repository = "https://github.com/tcharding/doge-wallet-rs/"
description = "Command line Dogecoin wallet"
keywords = [ "crypto", "dogecoin" ]
readme = "README.md"

[dependencies]
anyhow = "1.0"
dogecoincore-rpc = { version = "0.13", git = "http://github.com/tcharding/rust-dogecoincore-rpc" }
dogecoin = { version = "0.26", git = "http://github.com/tcharding/rust-dogecoin"}
# doge-bdk = { version = "0.9.1-dev", features = [ "rpc" ], default-features = false, git = "http://github.com/tcharding/doge-bdk" }
doge-bdk = { version = "0.9.1-dev", features = [ "rpc" ], default-features = false, path = "../doge-bdk"}
env_logger = "0.8"
log = { version = "0.4", features = ["std"] }
structopt = "0.3"
