[package]
name = "doge-wallet"
version = "0.1.0"
edition = "2018"
authors = ["Tobin Harding <me@tobin.cc>"]
license = "MIT"
homepage = "https://github.com/tcharding/doge-wallet-rs/"
repository = "https://github.com/tcharding/doge-wallet-rs/"
description = "Command line Dogecoin wallet"
keywords = [ "crypto", "dogecoin" ]
readme = "README.md"

[dependencies]
anyhow = "1.0"
dogecoin = { path = "../rust-dogecoin"}
env_logger = "0.8"
log = { version = "0.4", features = ["std"] }
structopt = "0.3"
