[package]
name = "doge-wallet"
version = "0.1.0"
edition = "2018"
authors = ["Tobin Harding <me@tobin.cc>"]
license = "MIT"
homepage = "https://github.com/tcharding/doge-wallet-rs/"
repository = "https://github.com/tcharding/doge-wallet-rs/"
description = "Command line Dogecoin wallet"
keywords = [ "crypto", "dogecoin" ]
readme = "README.md"

[dependencies]
anyhow = "1.0"
bitcoincore-rpc = "0.13"
bitcoin = "0.26"
bdk = { version = "0.9", features = [ "electrum", "key-value-db" ], default-features = false }
electrum-client = "0.7"
env_logger = "0.8"
log = { version = "0.4", features = ["std"] }
secp256k1 = "0.20"
serde_json = "1.0"
sled = "0.34"
structopt = "0.3"
